name: "Unit Tests"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: make test
      run: |
        make test
